name: Lint, Test & Scripts
on: push
jobs:
  dependencies:
    runs-on: macos-latest
    steps:
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
  lint:
    needs: dependencies
    runs-on: macos-latest
    steps:
      - name: Lint
        run: npm run lint
  test:
    needs: lint
    runs-on: macos-latest
    steps:
      - name: Test
        run: npm run test
  build:
    needs: test
    runs-on: macos-latest
    steps:
      - name: Build
        run: npm run build