name: Lint, Test & Scripts
on: push
jobs:
  lint:
    runs-on: macos-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
  test:
    needs: lint
    runs-on: macos-latest
    steps:
      - name: Test
        run: npm run test
  build:
    needs: test
    runs-on: macos-latest
    steps:
      - name: Build
        run: npm run build
  deploy:
    needs: build
    runs-on: macos-latest
    steps:
      - name: Deploy code
        run: echo "Deploying..."
